package com.miniProject.Carpool.model;

public enum CancelReason {
    CHANGE_OF_PLAN,
    FOUND_ALTERNATIVE,
    DRIVER_DELAY,
    PRICE_ISSUE,
    WRONG_LOCATION,
    DUPLICATE_OR_WRONG_DATE,
    SAFETY_CONCERN,
    WEATHER_OR_FORCE_MAJEURE,
    COMMUNICATION_ISSUE
}